# Generated by Django 5.1.1 on 2024-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=10)),
                ('revision', models.IntegerField()),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('sequence_number', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=10)),
                ('date_of_production', models.IntegerField()),
                ('history_of_module', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
