# Generated by Django 5.1.1 on 2024-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=10)),
                ('revision', models.IntegerField()),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('sequence_number', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=10)),
                ('date_of_production', models.IntegerField()),
                ('history_of_module', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='regi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('MU', 'Модули управляющие'), ('MVVS', 'Модули ввода-вывода сигналов')], max_length=20, verbose_name='Семейство')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('module_count', models.PositiveIntegerField(unique=True, verbose_name='Количество модулей')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('history', models.TextField(blank=True, max_length=10000, verbose_name='История модуля')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
