# Generated by Django 5.1.1 on 2024-10-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_modules_product_family'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modules',
            table=None,
        ),
    ]
