# Generated by Django 5.1.1 on 2024-10-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_regi_module_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regi',
        ),
    ]
