# Generated by Django 5.1.1 on 2024-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('MU', 'Модули управляющие'), ('MVVS', 'Модули ввода-вывода сигналов'), ('MR', 'Модули расширения'), ('MD', 'Модули диагностики'), ('MVVS_SPIN', 'Модули ввода-вывода сигналов СПиН'), ('KP', 'Объединительные платы'), ('BOS', 'Оптические свитчи, коммутаторы'), ('BV', 'Блоки питания'), ('SK', 'Соединители клеммные'), ('KABELS', 'Кабельная продукция'), ('KONSTRUCTIVEELEMINT', 'Конструктивный элемент')], max_length=20, verbose_name='Семейство')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('module_count', models.PositiveIntegerField(verbose_name='Количество модулей')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('history', models.TextField(blank=True, max_length=10000, verbose_name='История модуля')),
            ],
        ),
    ]
