# Generated by Django 5.1.1 on 2024-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proverka',
            fields=[
                ('proverka_id', models.AutoField(primary_key=True, serialize=False)),
                ('proverka_otchet', models.CharField(max_length=1000000, verbose_name='Отчет')),
                ('proverka_info', models.CharField(max_length=1000000, verbose_name='Информация')),
                ('proverka_error', models.CharField(max_length=1000000, verbose_name='Возможная причина ошибки')),
            ],
        ),
    ]
