# Generated by Django 5.1.1 on 2024-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='history',
            field=models.TextField(max_length=10000, verbose_name='История модуля'),
        ),
    ]
