# Generated by Django 5.1.1 on 2024-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reg_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='family',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='type',
        ),
        migrations.AddField(
            model_name='reg',
            name='ec_number',
            field=models.CharField(default='', max_length=255, verbose_name='Номер ец'),
            preserve_default=False,
        ),
    ]
