# Generated by Django 5.1.1 on 2024-10-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_proverka_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalibrovka',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='poverka',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='remont',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='transportirovka',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='proverka',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', on_delete=django.db.models.deletion.CASCADE, to='main.serial_numbers', to_field='combined_field', verbose_name='Серийный номер'),
        ),
    ]
