# Generated by Django 5.1.1 on 2024-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_info_modules_delete_info_modules_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_modules',
            name='info_product_family_code',
            field=models.PositiveIntegerField(default=1, verbose_name='Код семейства продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info_modules',
            name='info_ec_number',
            field=models.CharField(max_length=100, verbose_name='Номер еЦ'),
        ),
    ]
