# Generated by Django 5.1.1 on 2024-10-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_spp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='number_of_module',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер изделия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info_modules',
            name='info_product_family',
            field=models.CharField(max_length=100, verbose_name='Семейство изделия'),
        ),
        migrations.AlterField(
            model_name='info_modules',
            name='info_product_family_code',
            field=models.PositiveIntegerField(verbose_name='Код семейства изделия'),
        ),
        migrations.AlterField(
            model_name='info_modules',
            name='info_product_type',
            field=models.CharField(max_length=100, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='info_modules',
            name='info_product_type_code',
            field=models.PositiveIntegerField(verbose_name='Код типа изделия'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='history',
            field=models.TextField(max_length=10000, verbose_name='История изделия'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='module_count',
            field=models.PositiveIntegerField(verbose_name='Количество изделий'),
        ),
    ]
