# Generated by Django 5.1.1 on 2024-10-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_info_modules_info_ec_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial_numbers',
            name='ser_info_manufacturer_code',
        ),
        migrations.RemoveField(
            model_name='serial_numbers',
            name='ser_info_product_family_code',
        ),
        migrations.RemoveField(
            model_name='serial_numbers',
            name='ser_info_product_type_code',
        ),
        migrations.RemoveField(
            model_name='serial_numbers',
            name='ser_info_revision_code',
        ),
        migrations.RemoveField(
            model_name='serial_numbers',
            name='ser_number_of_module',
        ),
        migrations.RemoveField(
            model_name='serial_numbers',
            name='ser_production_date',
        ),
        migrations.AddField(
            model_name='serial_numbers',
            name='combined_field',
            field=models.TextField(blank=True, verbose_name='Объединенное поле'),
        ),
    ]
